### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by harikt** [slimphp/Slim-Csrf#1]
Hi Josh Lockhart, 

I don't believe mt_rand is a nice candidate.  So the line 

```
$token = hash("sha512", mt_rand(0, mt_getrandmax()));
```

seems not safe to me. I don't recall the discussion thread, but there was one.

It was also in @auraphp Session . See commit https://github.com/auraphp/Aura.Session/commit/7e3c8360ff4f5f34d09d87a599a1ac527dbb054a 

Later iirc after reviewed by ircmaxwell , it was changed to make use of a RandomInterface, via which you can incorporate something like RandomLib or Random generators.

It will be nice, if there is a way we can incorporate libraries. So only need to deal with one library for security.

https://github.com/auraphp/Aura.Session#defending-against-csrf

Thanks!

**Comment by geggleto** [comment]
This code was taken from the OWASP wiki.
Ref: https://www.owasp.org/index.php/PHP_CSRF_Guard

The encryption dependencies were recently removed from Slim Core, but I would like to see this modified such that, if more secure extensions exist, then use them.

/cc @codeguy

**Comment by codeguy** [comment]
:+1: Agreed. We were chatting about this in irc the other day. If anyone wants to send a PR that uses more secure extensions, please do. I'm working on other issues right now.

**Comment by harikt** [comment]
Hi @codeguy , 

If you are ok with Aura.Session I can send a PR for the same.

**Comment by codeguy** [comment]
There's already a pr open that is addressing this. Thanks though!

**Comment by harikt** [comment]
ok. Thanks!

**Comment by geggleto** [comment]
Now uses open ssl if available.

**Comment by masakielastic** [comment]
It would be nice to support `hash_equals` (PHP 5.6) and `random_bytes` (PHP 7.0: [RFC](https://wiki.php.net/rfc/easy_userland_csprng)). WordPress uses `hash_equals` in `wp_verify_nonce`.

**Comment by geggleto** [comment]
@masakielastic created issue, #3 

I don't have the time until about Thursday. You are welcome to change it!

**Comment by codeguy** [comment]
I'm busy today, but if anyone wants to send a pr I'll be happy to merge.
