### ISSUE TITLE
1.0.0 throws errors at Slim 3

### ISSUE THREAD

**Issue by terrylinooo** [slimphp/Slim-Csrf#109]
Hello.

As post title, 1.0.0 throws parameter errors at Slim 3.

When I remove it and go back to install the older version and it works well.

```
composer require slim/csrf:0.8.3
```

**Comment by l0gicgate** [comment]
That’s because 1.0.0 is only compatible with Slim 4

**Comment by ve3** [comment]
No [change log](https://github.com/slimphp/Slim-Csrf/blob/master/CHANGELOG.md)?
Changed removed etc?
