### ISSUE TITLE
How to integrate slim-session

### ISSUE THREAD

**Issue by Regaddi** [slimphp/Slim-Csrf#114]
Hey!

I'd like to integrate slim-csrf (v0.8.3) with https://github.com/bryanjhv/slim-session (v3.0).
It seems that slim-csrf directly accesses `$_SESSION`, but I'd need it to utilize `new \SlimSession\Helper()` instead.
Is this achievable? I'd like to avoid having to upgrade my complete application from slim3 to slim4.

Thanks in advance!

**Comment by l0gicgate** [comment]
You can provide your own storage from within the `Guard` constructor or via the `Guard::setStorage()` method.
