### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by schiederme** [slimphp/Slim-Csrf#128]
Hey, I ruined into the following error:
` Problem 1
    - Root composer.json requires slim/csrf ^1.0.0 -> satisfiable by slim/csrf[1.0.0].
    - slim/csrf 1.0.0 requires php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
`

My 'testing' solution is removing the required for now and add it manually as remote repository in composer.

Besides that PHP7.1 is (if im right) EOL.

Thanks,
Maxi

**Comment by schiederme** [comment]
Ohhh 

If installed, with requires php^7.1 its throws the following error on the slim project:
`[Wed Jan  6 01:29:54 2021] PHP Fatal error:  Uncaught TypeError: rtrim(): Argument #1 ($string) must be of type string, Slim\Psr7\Factory\ResponseFactory given in /Users/maxi/Desktop/Workspace/schiederme/slim/vendor/slim/csrf/src/Guard.php:97
Stack trace:
`

**Comment by schiederme** [comment]
Running composer install with  --ignore-platform-reqs fix the issue too, so my testing solution is nonsense.

**Comment by schiederme** [comment]
Ok, thank you. I will just use ignore platform for now. If you want, you can close this or let it open for other people (for now.)

**Comment by hkvstore** [comment]
> ` Root composer.json requires slim/csrf ^1.0.0 -> satisfiable by slim/csrf[1.0.0]. - slim/csrf 1.0.0 requires php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.`

The composer.json of just released v1.1.0 still requires ``"php": "^7.1"``. Does the new version support PHP 8?

Thanks.

**Comment by akrabat** [comment]
We need to update the travis configuration to test on PHP8 to find out.

**Comment by akrabat** [comment]
[Slim-Csrf 1.2.0](https://github.com/slimphp/Slim-Csrf/releases/tag/1.2.0) released which will install on PHP 8.

**Comment by hkvstore** [comment]
Thank you very much. However, the current version of Slim still requires ``"php": "^7.2 || ^8.0"``, it would be nice if the requirements can be in sync. (Slim requires ^7.3 or Slim-Csrf supports ^7.2.)
