### ISSUE TITLE
Not working with slim-session package?

### ISSUE THREAD

**Issue by inpresif** [slimphp/Slim-Csrf#168]
Hi,

I've been trying to add this for a while now, using the https://github.com/bryanjhv/slim-session package.
Unfortunately I keep getting the following error:

`Fatal error: Uncaught RuntimeException: Invalid CSRF storage. Use session_start() before instantiating the Guard middleware or provide array storage. `

I have tried moving the session contained in each poaition possible (top to bottom), but it's not working out. When I remove the sessions extension and just use session_start() it is working, but I'd love to use both :)

Is it okay to assume this is not going to work with this custom session package? Do you maybe have an idea how to "fix" it?

Much appreciated!

**Comment by blablabla1234678** [comment]
Not working at all here. The values are empty. Better to use my own module for this.

**Comment by l0gicgate** [comment]
That package is not compatible with Slim-Csrf's current version unfortunately.

**Comment by dfranco** [comment]
@inpresif If it can help, I confirm it works using https://github.com/odan/session with Slim version 4.12.
