### ISSUE TITLE
CSRF failure needs to be customisable

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim-Csrf#17]
When the CSRF fails, then this code is executed: `return $response->withStatus(400);`

This results in a blank browser. Ideally, I would would to display the form again with an error message at the top saying that there was a failure.

**Comment by codeguy** [comment]
How do you want to approach this? Should we allow user to inject a callback to be invoked in this scenario? Or should we just toss an exception that can be caught and handled elsewhere?

**Comment by akrabat** [comment]
That's a good question.

I wonder if we can allow registration of a callable that has the same signature as middleware with a default one that looks like:

```php
function ($request, $response, $next) {
    $body = new \Slim\Http\Body('php://temp');
    $body->write('Failed CSRF check!');
    return $response->withStatus(400)->withBody($body);
};
```

This way someone can override and throw an exception or add an attribute to `$request`, call `return $next($request, $response);` and do something with that attribute later.

Thoughts?

**Comment by JoeBengalen** [comment]
Maybe just put the error handler into its own method, which is easy to override by extending the Guard

**Comment by akrabat** [comment]
Writing an extended class seems overkill to throw an exception and still doesn't allow the route callable to take control if it wanted to. Unless the error-handler used the middleware signature, I suppose.

**Comment by wforums** [comment]
I quite like the set up you added today. It's a nice improvement over the blank page that was rendered, as I can now show the form again. :+1:

**Comment by akrabat** [comment]
Fixed.
