### ISSUE TITLE
csrf with fetch and ajax requests

### ISSUE THREAD

**Issue by athagiorgos** [slimphp/Slim-Csrf#189]
I have installed the package and works with every form submission. However there are some fetch POST requests in the frontend and then the csrf fails, returning a bad request. I teid sending it over body and headers

```
const response = await fetch(`/blogposts/delete/${window.blogId.trim()}`, {
        method: 'DELETE', // other requests are POST and fail also
        headers: {
            "csrf_name": csrf_name,
            "csrf_value": csrf_value
        },
    });
```

but it does not seem to work. Should is check for these requests manually?

Thanks in advance

**Comment by odan** [comment]
I think this issue relates to this:

> By default, Slim\Csrf\Guard will generate a fresh name/value pair after each request.
> ...
> To use persistent tokens, set the sixth parameter of the constructor to true. No matter what, the token will be regenerated after a failed CSRF check.

Can you try to enable the "persistence mode"?

```php
$guard = new Guard($responseFactory);
$guard = $guard->setPersistentTokenMode(true);

return $guard;
```

More details:

* https://github.com/slimphp/Slim-Csrf?tab=readme-ov-file#token-persistence
* https://github.com/slimphp/Slim-Csrf/issues/49

**Comment by athagiorgos** [comment]
I already have "persistence mode" set to true. Does the guard middleware check for csrf_name and csrf_value only from form fields in a request? Because the functionality i am getting seems like it.

**Comment by odan** [comment]
In your example you are using the DELETE http method, so in in case the keys should be provided in the request header using the correct (this means the configured) key names. So your example looks correct. 

> // DELETE request may not have a request body. Supply token by headers

https://github.com/slimphp/Slim-Csrf/blob/1.x/src/Guard.php#L449-L452

You may try to use Xdebug or print the following values to get the real key names:

```php
 $nameKey = $csrf->getTokenNameKey();
 $valueKey = $csrf->getTokenValueKey();
```

PS: Also make sure that the session handler is started correctly.
