### ISSUE TITLE
Don't regenerate token on each request?

### ISSUE THREAD

**Issue by vlakoff** [slimphp/Slim-Csrf#22]
I load two pages with form, in different browser tabs. As the CSRF token is regenerated on each request (GET as well as POST), the first form will fail submitting.

If this issue is worked on, here is the next pitfall to expect: Submitting a form shouldn't make the other forms, opened in other tabs already, to fail.

I had a look at Laravel, it generates the token only if it doesn't exist yet. It never regenerates it, even after a form submission. ([VerifyCsrfToken.php](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php), [Store.php](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Session/Store.php))

**Comment by geggleto** [comment]
This is intentional behaviour.

**Comment by akrabat** [comment]
This drives me up the wall too...

**Comment by akrabat** [comment]
Looking at it, this is not a problem with the current implementation.

Each request, a new token with a unique name is generated. Thus you can have multiple tabs open on different forms and it works as expected as each form uses a differently named token.

**Comment by vlakoff** [comment]
akrabat you are right, I had overlooked the `$name = $this->prefix . mt_rand(0, mt_getrandmax());`, tokens have different names and validate independently. (though, I think the names should have more entropy)

As a consequence, new tokens don't replace the first one but are added up, one more token is stored on each request. I was going to bring the issue, but you already have spotted and fixed it in #23, thanks :)
