### ISSUE TITLE
Change MT_RAND

### ISSUE THREAD

**Issue by geggleto** [slimphp/Slim-Csrf#26]
Change mt_rand and mt_getrandmax ... etc to cryptographically secure functions 

https://github.com/paragonie/random_compat

Future proofs as well by using PHP 7 functions.

PR will come once the reference project gets tagged 1.0.0

**Comment by geggleto** [comment]
This should be available next week.

**Comment by akrabat** [comment]
I'm definitely a big fan of replacing our code with `random_compat`!

**Comment by geggleto** [comment]
Yeah I just haven't found the time :/ ...
