### ISSUE TITLE
How to validate subsequent AJAX requests?

### ISSUE THREAD

**Issue by ryanscherler** [slimphp/Slim-Csrf#32]
It seems to work on the first submit, but if submitted again, the tokens are invalid. Any strategies on how to refresh tokens for subsequent Ajax requests with the need for 'refreshed' tokens to pass along?

**Comment by ryanscherler** [comment]
I assume that maybe setting a cookie after the first attempt (when the CSRF initially passes) via PHP and then subsequent Ajax calls would check the cookie via JS and pass in the refreshed token? Seems like there would be a way to persist for Ajax - just not sure

**Comment by geggleto** [comment]
Hi @ryanscherler,

There are a few solutions,

1) What you will want to do is generate a new token pair after consuming a pair. You can store this in your app [I assumed you were using something like Angular or a single page app]

2) When you generate a client side form you include a page that generates the token pair as hidden input fields / or to just retrieve the token pair. you would use a GET request to include the token pair and include it in your form.

**Comment by ryanscherler** [comment]
Hi Glenn,

Thanks for the info. Here's my scenario that could implement (in a way) what you've outlined.

1. I have a Twig template that renders a form with the hidden token input fields (not an angular or otherwise dynamic form)

2. That form posts via $.ajax({...}) to a form processor endpoint (/api/form/)

3. That form processes the POST ($request->getParsedBody() etc.), validates the token via the middleware failureCallable method (as well as validating the other fields) and returns either a JSON error or success response.

This works great on the first submission. Once the token is consumed, subsequent submissions cause the CSRF error. One idea I had was to return a new token pair as part of the request header that is returned to the ajax response. My script could then parse the headers, grab the newly generated token set and then swap those values with the ones already in the form? Seems like a bit more work but may very well be the way I have to do it. I do recall something with Laravel that allows a sort of persistence of the token once verified via AJAX, but that may be something that just isn't going to happen with this particular middleware implementation.

Thanks for the info and I look forward to your opinion on this possible "pass back via headers" strategy for persisting / getting new CSRF token(s).

**Comment by geggleto** [comment]
I also thought of passing back via headers, but I hated how much extra work that was on the client side to do. 

If you want to raise an issue about adding persistence to the library... I think there might be a valid use case there. 
The fix is a guard around 
[ https://github.com/slimphp/Slim-Csrf/blob/master/src/Guard.php#L204 ], using what I think would be a controllable setting. We would keep the default currently which would be "strict" => true

It should also be noted that there may only ever be 1 active key-pair ... 
[ https://github.com/slimphp/Slim-Csrf/blob/master/src/Guard.php#L291 ]

I don't think that is documented anywhere...

**Comment by ryanscherler** [comment]
yeah - I am not super excited to implement this option for getting the new token from the headers, but I may go this route for now.

I'll go ahead and close this issue and create a new one that outlines the use case above and a link to the thread here with a possible guard setting on the removal of the token.

Thanks!

**Comment by ryanscherler** [comment]
Okay - issue noted ;-)

https://github.com/slimphp/Slim-Csrf/issues/33

Closing this thread.

Thanks again @geggleto !

**Comment by akrabat** [comment]
> It should also be noted that there may only ever be 1 active key-pair ... [ https://github.com/slimphp/Slim-Csrf/blob/master/src/Guard.php#L291 ]

Actually - there can be up to `storageLimit` active pairs. The default is 200.

**Comment by ryanscherler** [comment]
What good does storing 200 active pairs if it seems to only check the latest (1 active key pair)? I am not sure how this works to my advantage on subsequent requests?

**Comment by emilkitua** [comment]
was this problem finally solved without editing [https://github.com/slimphp/Slim-Csrf/blob/master/src/Guard.php#L204]????????

**Comment by akrabat** [comment]
@emilkitua: Set the constructor parameter `$persistentTokenMode` to `true`

**Comment by emilkitua** [comment]
thank you

**Comment by emilkitua** [comment]
i am trying it on the following ajax code:

`function getDistricts(){
                                var r_id = document.getElementById("region").value;
                                var csrfName = document.getElementById('csrf_name').value;
                                var csrfValue = document.getElementById('csrf_value').value;
                                console.log(r_id);
                                // console.log(csrfValue);
                                var datastring = {"id" : r_id, "csrf_name" : csrfName, "csrf_value" : csrfValue};
                                $.ajax({
                                    type:'POST',
                                    url:'{{ base_url() }}/reports/districts',
                                    data:datastring,
                                    success:function(data){
                                        console.log(data);
                                        item = [];
                                        for (var i=0; i < data.length; i++)
                                        {
                                            $("#district").html(data);
                                            var district = myTrim('<option value="' + data[i].d_id + '">' + data[i].d_name + '</option>');
                                            item.push(district);
                                            //$("#district").appendAdd(district);
                                            console.log(district);
                                        }
                                        $("#district").append(item);
                                        // console.log(district);
                                    }
                                });
                            }

                            function getHospital(){
                                var d_id = document.getElementById("district").value;
                                var csrfName = document.getElementById('csrf_name').value;
                                var csrfValue = document.getElementById('csrf_value').value;
                                var datastring = {"id" : d_id, "csrf_name" : csrfName, "csrf_value" : csrfValue};
                                // console.log(datastring);
                                
                                $.ajax({
                                    type:'POST',
                                    url:'{{ base_url() }}/reports/hospital',
                                    data:datastring,
                                    success:function(data){
                                        console.log(data);

                                        item = [];
                                        for (var i=0; i < data.length; i++)
                                        {
                                            $("#hospital").html(data);
                                            var hospital = myTrim('<option value="' + data[i].d_id + '">' + data[i].d_name + '</option>');
                                            item.push(hospital);
                                            //$("#hospital").appendAdd(hospital);
                                            console.log(hospital);
                                        }
                                        $("#hospital").append(item);
                                        // console.log(hospital);
                                    }
                                });
                            }`

on the first one get districts it is working, but on the second one get hospitals it is returning ERROR: 500 (Internal Server Error)

**Comment by akrabat** [comment]
Please ask support questions on discourse.slimframework,com.

**Comment by emilkitua** [comment]
okay thanks

**Comment by akrabat** [comment]
@mridah It's the last parameter to the constructor: https://github.com/slimphp/Slim-Csrf/blob/master/src/Guard.php#L89-L96
