### ISSUE TITLE
Add Persistence Option / Guard for Tokens

### ISSUE THREAD

**Issue by ryanscherler** [slimphp/Slim-Csrf#33]
It would be great to have a way to 'persist' tokens for subsequent attempts on requests. Please take a look at this issue which [outlines a valid use case](https://github.com/slimphp/Slim-Csrf/issues/32#issuecomment-151916726) for such a scenario.

Via @geggleto 

> The fix is a guard around 
[ https://github.com/slimphp/Slim-Csrf/blob/master/src/Guard.php#L204 ], using what I think would be a controllable setting. We would keep the default currently which would be "strict" => true

**Comment by geggleto** [comment]
Will add to my to do list for tonight for PR.

**Comment by geggleto** [comment]
See #34

**Comment by akrabat** [comment]
I'm not a fan of the token persisting.

Best practice appears to be the `X-CSRF-Token` header:

* https://en.wikipedia.org/wiki/Cross-site_request_forgery#Cookie-to-Header_Token
* http://security.stackexchange.com/questions/36468/csrf-protection-and-single-page-apps

**Comment by ryanscherler** [comment]
I agree that persisting these tokens is not the best way to go. Though I am still having issues wrapping my head around how to pass things back and forth in an HXR application with the given Middleware. It would be nice to see a quick sample of how one might accomplish this in Slim.

**Comment by geggleto** [comment]
@ryanscherler 

```
$.ajax({
   type: 'POST',
   url:'url.do',
   data: formData,
   success: function(data, textStatus, request){
        alert(request.getResponseHeader('some_header'));
   },
   error: function (request, textStatus, errorThrown) {
        alert(request.getResponseHeader('some_header'));
   }
  });
```
http://stackoverflow.com/questions/1557602/jquery-and-ajax-response-header

**Comment by ryanscherler** [comment]
So I would set some middleware to generate the token and attach to a $request header? 

Somehow I would then need to send that data (or replace the existing token form field values) and send the form again? (Since it seems the middleware checks for POSTed values?

**Comment by ryanscherler** [comment]
The issue here is not the initial form submission, but rather subsequent submissions - like a validation faulre (thats when the stale token issue happens)

**Comment by geggleto** [comment]
1) Middleware to generate a new keypair
2) Attach keypair to response

**Comment by geggleto** [comment]
```
$myRegenerator = function ($request, $response, $next) {

$res = $next($request, $response);

//Generate new Keypair

//Attach to response
return $res;
};

$app->post(...)->addMiddleware($myRegenerator);

**Comment by ryanscherler** [comment]
Gotcha - thanks!

**Comment by geggleto** [comment]
Glad you could follow the mobile pseudo code haha

**Comment by ryanscherler** [comment]
Seems I am able to use a middleware to attach the token, but for some reason the token values are returned null? See my [updated comment here](#issuecomment-152255738) with attached code.

I am attaching my middleware AFTER the CSRF:

```
// Dependencies

// CSRF
$container['csrf'] = function($c) {
    return new \Slim\Csrf\Guard;
};

$container['csrf.header'] = function($c) {
    return new App\Middleware\CsrfResponseHeader($c->get('csrf'));
};

// Middleware

$app->add($container->get('csrf'));
$app->add($container->get('csrf.header'));
```

**Comment by geggleto** [comment]
You need to create a new keypair by using Guard::generateNewToken

**Comment by geggleto** [comment]
Looking at this code, we can refactor that coupling in a future PR...
A token should not depend on a Request Object at least in this use case.

**Comment by ryanscherler** [comment]
I wish I could generate a new key pair - but its a protected function:

 Call to protected method Slim\Csrf\Guard::generateNewToken()

**Comment by geggleto** [comment]
Okay I will PR that..

**Comment by ryanscherler** [comment]
Sounds good. I went ahead and set the method to public and updated my middleware as follows and it works!

```
namespace App\Middleware;

use \Slim\Csrf\Guard;

class CsrfResponseHeader
{

    private $csrf;

    public function __construct(Guard $csrf)
    {
        $this->csrf = $csrf;
    }

    /**
     * Example middleware invokable class
     *
     * @param  \Psr\Http\Message\ServerRequestInterface $request  PSR7 request
     * @param  \Psr\Http\Message\ResponseInterface      $response PSR7 response
     * @param  callable                                 $next     Next middleware
     *
     * @return \Psr\Http\Message\ResponseInterface
     */
    public function __invoke($request, $response, $next)
    {     
        // Generate new token and update request
        $request = $this->csrf->generateNewToken($request);
        
        // Build Header Token
        $nameKey = $this->csrf->getTokenNameKey();
        $valueKey = $this->csrf->getTokenValueKey();
        $name = $request->getAttribute($nameKey);
        $value = $request->getAttribute($valueKey);
        $tokenArray = [
            $nameKey => $name,
            $valueKey => $value
        ];
        
        // Update response with added token header
        $response = $response->withAddedHeader('X-CSRF-Token', json_encode($tokenArray));

        return $next($request, $response);
    }
}
```

**Comment by geggleto** [comment]
Excellent. just in the middle of the PR now.

**Comment by geggleto** [comment]
See #35

**Comment by geggleto** [comment]
Found this in a TwgiHelper ...

`
        $nameKey = $this->guard->getTokenNameKey();
        $valueKey = $this->guard->getTokenValueKey();
        $nameValue = $this->guard->getKeyPair()[$nameKey];
        $valueValue = $this->guard->getKeyPair()[$valueKey];
`

**Comment by aurmil** [comment]
faced the same problem, found this thread, allowed myself to create a middleware
https://github.com/aurmil/slim3-csrf-utilities

**Comment by Simplesmente** [comment]
Hi there i have been some problems for implement the csrf_token using api fetch of javascript. I tried implement the class above that @ryanscherler wrote, and don't works. I don't know what i do else. 

see my class Js:
```
class LoginController {

	constructor() {

		this.username = document.querySelector("#username");
		this.password = document.querySelector("#password");
		this.csrfName = document.querySelector("#csrf_name");
		this.csrfValue= document.querySelector("#csrf_value"); 
	}

	doLogin(e){

		e.preventDefault();
	
		const header = new Headers();
	
		let params = {
			url:'http://localhost:8080/sigin',
			verb: {
				method: 'POST',
				headers: new Headers({'Content-Type':'application/json',
										'X-CSRF-Token':{
											'csrf_name':this.csrfName.value,
											'csrf_value': this.csrfValue.value,
										}
						}),
// Already tried pass the token here into body request, and don't works.

				body: JSON.stringify({'name':'some teste' })	
			}
		}

		fetch(params.url, params.verb)
			.then( response => {
				console.log(response);
			});

	}
}
 
```

Now my implementation with slim:

`<?php
namespace ContaAzul\Middlewares;

use \Slim\Csrf\Guard;

class CsrfResponseHeader
{

    private $csrf;

    public function __construct(Guard $csrf)
    {
        $this->csrf = $csrf;
    }

    /**
     * Example middleware invokable class
     *
     * @param  \Psr\Http\Message\ServerRequestInterface $request  PSR7 request
     * @param  \Psr\Http\Message\ResponseInterface      $response PSR7 response
     * @param  callable                                 $next     Next middleware
     *
     * @return \Psr\Http\Message\ResponseInterface
     */
    public function __invoke($request, $response, $next)
    {        

        $response = $next($request, $response);
        
        $nameKey = $this->csrf->getTokenNameKey();
        $valueKey = $this->csrf->getTokenValueKey();
        $name = $request->getAttribute($nameKey);
        $value = $request->getAttribute($valueKey);
        $tokenArray = [
            $nameKey => $name,
            $valueKey => $value
        ];
        $response = $response->withAddedHeader('X-CSRF-Token', json_encode($tokenArray));
        return $response;
    }
}`

And added the middleware above in my route:

```
$app->post('/sigin',['ContaAzul\Controllers\LoginController','postSigin'])
										->add(new ContaAzul\Middlewares\CsrfResponseHeader($guard));
```


Someone can help me ?

**Comment by avdwalt** [comment]
Simplesmente - did you ever get your issue resolved?

**Comment by GazEdBro** [comment]
Hi I was looking for solutions to this issue and eventually came here.  But the apparent solution:
Middleware to generate a new keypair
Attach keypair to response
Is I think flawed, since it is inherently a synchronous approach and ajax is asynchronous - certainly there would/could be lots of failures in the case I am working on - responding to typing letter-by-letter.  I therefore am going to look to avoid regenerating the keypair in the case of an ajax request.  So the security depends on:
Initial CSRF check,
User logged in,
Specific URLs persist keypair
HTTPS.
At the moment I can't think of anything better - but putting this out there for correction!
