### ISSUE TITLE
Session filling up

### ISSUE THREAD

**Issue by designermonkey** [slimphp/Slim-Csrf#37]
Is this supposed to generate a new key => value for every page load?

I am testing a session component and had this middleware activated. Whenever I refresh the page, another pair is added, and none are cleaned up.

**Comment by akrabat** [comment]
Yes. It clears up after 200 iirc - there's a setting for it.

**Comment by akrabat** [comment]
It works this way so that you can open a form in a tab and then browse the site in another tab and not lose the CSRF token for the form

**Comment by designermonkey** [comment]
I just read the code and spotted that, thanks.

Guess I should RTFM eh? :D

**Comment by akrabat** [comment]
Feel free to PR an update to the README :)
Though we should probably check the docs on Slim-Website too

**Comment by geggleto** [comment]
I am pretty sure 200 is a bit excessive, but I think that is left for another issue
