### ISSUE TITLE
Option to whitelist routes

### ISSUE THREAD

**Issue by alexweissman** [slimphp/Slim-Csrf#45]
Right now, we can use the CSRF middleware in one of two ways: either applied to [all routes](https://github.com/slimphp/Slim-Csrf#register-for-all-routes), or on a [route-by-route basis](https://github.com/slimphp/Slim-Csrf#register-per-route).

It would be nice if there were an option to whitelist certain routes, so that CSRF checks are performed on all routes **except** those explicitly listed.

**Comment by geggleto** [comment]
You can currently use route groups to accomplish what you are requesting.

**Comment by alexweissman** [comment]
Whoa, that is a pretty cool feature - thanks for pointing it out to me.  However, I'm not sure it is exactly equivalent.  With route groups, I'd have to place all my routes (except the ones I want to exempt from CSRF) in a single group, right?

It seems like routes are more for semantically grouping routes based on the type of resource, which may or may not correspond to CSRF exemption.

**Comment by geggleto** [comment]
yeah it is a bit "weird" but you can totally accomplish what you are looking for in a group like

```php $app->group('', function ( ...```

**Comment by schnittstabil** [comment]
> It seems like routes are more for semantically grouping routes based on the type of resource, which may or may not correspond to CSRF exemption.

CSRF protection is about protecting resources, thus they and their groups usually correspond to your CSRF exemptions.

> It would be nice if there were an option to whitelist certain routes…

Routes contain more information than an URI pattern (e.g. method information), therefore white-listing at `Guard` `__construct` is complicated – apart from that, it would be bad practice. 

But white-listing at route creation would be nice:

```php
$app->post('/api/myEndPoint',function ($req, $res, $args) {
    // …
})->add($container['csrf']->whitelist());
```

Or, much easier to implement:
```php
$container['csrf']->whitelist($app->post('/api/myEndPoint',function ($req, $res, $args) {
    // …
}));
```

**Comment by geggleto** [comment]
What you will need to do is write a different Middleware class or extend from Guard to implement your requested features.

**Comment by alexweissman** [comment]
Ah yes, @schnittstabil's suggestion makes sense.  Actually, with named routes, it could still be possible to declare them in a single place.  But in this case, I'm still not sure what would be "best practice".

**Comment by geggleto** [comment]
You are getting into the realm of requiring something custom ;)

you can just define your own guard class by extending it and just override the invoke.

I think that would be best practice.

**Comment by schnittstabil** [comment]
> Actually, with named routes, it could still be possible to declare them in a single place.

IMO, declaring which routes should be CSRF-protected in a single place, isn't good practice: if you want to add/remove a route, you'll have to make changes at two different places.

**Comment by geggleto** [comment]
Also it should be noted that you can cache the return's of the $app->verb methods then apply CSRF in a bulk manner.

```php
$csrf[] = $app->get( ... )
foreach ($csrf as $route) { $route->add(Guard::class); }
```

**Comment by Shelko** [comment]
Hi, i'm using Slim Framework as my first framework and i saw videos about how works it. It's simple and great but i have hm... doubts...

 I'm doing a web service with Csrf and works well but i have problems cause i'm trying to **sign up** or **sign in** with a **smartphone**. Well... I did **ajax** the problem is the **CSRF** i'm trying to **disable** for **some** kind of **routes** without success. 

I'm trying to find an example for **dummies** ^^'.

I tried to delete the "add(container->csrf)" from kernel to add it to every route but it doesn't work.

Thanks for your time!

**Comment by alexweissman** [comment]
@Shelko we solved this in UserFrosting by conditionally adding the global middleware after checking the URL path against a blacklist in our configuration.  See https://github.com/userfrosting/UserFrosting/blob/67f846a76ce4c3a7ad92f6c7f215535bab123285/app/sprinkles/core/src/Core.php#L34-L61

Not the most elegant solution, but it works.

**Comment by akrabat** [comment]
Plenty of good suggestions here.
