### ISSUE TITLE
Storage limit is not enforced during failed POST

### ISSUE THREAD

**Issue by Dravere** [slimphp/Slim-Csrf#47]
If a POST, PUT, DELETE, PATCH fails the storage limit is not enforced. I set the storage limit to one in the hopes that always only one valid CSRF token was available. But when the check failed it didn't enforce the limit thus making two CSRF available at the same time.

**Comment by arvindpdmn** [comment]
A somewhat related clarification since I don't understand sessions very well. Currently (v1.2.1), storage limit defaults to 200. What happens if more than 200 people are accessing the site?
