### ISSUE TITLE
Session storage validation

### ISSUE THREAD

**Issue by ivandokov-shtrak** [slimphp/Slim-Csrf#53]
I am trying to implement @akrabat's Session Middleware and Slim-Csrf middleware together, but the validation in the `__construct` is blocking me (or I don't see the correct way).

I am registering both middlewares as follows:

```
$app->add(new \RKA\SessionMiddleware(['name' => 'session']));
$app->add(new \Slim\Csrf\Guard);
```

but I always get **CSRF middleware failed. Session not found**. Changing the order of the registration of these middlewares is not helping either. I think the reason is that the validation for existing session is done at initialization of the Guard class and this is not giving change of the previous middleware to start the session because it's not yet invoked.

**Comment by akrabat** [comment]
I bet that most of the constructor to `Guard` could be done at `__invoke` time.

**Comment by ivandokov** [comment]
@akrabat can you please take a look at this PR https://github.com/slimphp/Slim-Csrf/pull/55

**Comment by aurmil** [comment]
hi
any news on how to make these 2 middlewares work together?

**Comment by ivandokov** [comment]
The PR is waiting for review. Hopefully @akrabat will have time to check it soon.
