### ISSUE TITLE
Random Compact Version Issue

### ISSUE THREAD

**Issue by KuroThing** [slimphp/Slim-Csrf#57]
The version constraints on the paragonie/random_compat package allow version 1.4.x to be installed, and version 1.4, the usage of OpenSSL was returned, to allow version 2 to completely and finally remove it.

OpenSSL, as explained on [ParagonIE's blog](https://paragonie.com/blog/2015/07/how-safely-generate-random-strings-and-integers-in-php), is not a secure random generator, and i believe if it's worth using a "secure" random generator, than even allowing an insecure option should not be permitted.

Resolving this would be as simple as changing the version constraints of paragonie/random_compat to `>=1.3 <1.4` or better yet, updating to Version 2. The only problem with this, is it will cause problems with other packages (EG: [Illuminate/Support](https://github.com/illuminate/support) has a [version constraint](https://github.com/illuminate/support/blob/7f4cad5f7ebe095540a92a1c4394cd1c9db7bcc0/composer.json) of `~1.4`)

**Comment by schnittstabil** [comment]
From the [random.php source (v1.4.1)](https://github.com/paragonie/random_compat/blob/v1.4.1/lib/random.php#L68):
> In order of preference:
> 1. Use libsodium if available.
> 2. fread() /dev/urandom if available (never on Windows)
> 3. mcrypt_create_iv($bytes, MCRYPT_DEV_URANDOM)
> 4. COM('CAPICOM.Utilities.1')->GetRandom()
> 5. openssl_random_pseudo_bytes() __(absolute last resort)__

And from [the CHANGELOG.md](https://github.com/paragonie/random_compat/blob/v2.0.2/CHANGELOG.md#version-200---2016-03-18):
> Version 2.0.0 - 2016-03-18
> __Due to downstream errors__, the OpenSSL removal now belongs in version 2.0.0.

@KuroThing Therefore depending on '^1.0|^2.0' looks reasonable to me.

**Comment by KuroThing** [comment]
I was going to suggest `^1|^2`, but i wasn't entirely sure if it was wise to allow the user to mistakenly use OpenSSL without knowing it because another library (Like Illuminate/Support) has a version constraint that allows OpenSSL.

Also imo, Error and failure is better than insecurity when expecting security.

**Comment by schnittstabil** [comment]
@KuroThing I think that should be handled by `random_compat` (see https://github.com/paragonie/random_compat/issues/108) – many packages are affected by that, and it is a problem iff `openssl_random_pseudo_bytes` is actually used.

**Comment by geggleto** [comment]
This should be dealt with, random_compat now `1 | 2`

**Comment by akrabat** [comment]
Fixed with version 0.7.0.
