### ISSUE TITLE
Adapter for Laravel sessions

### ISSUE THREAD

**Issue by alexweissman** [slimphp/Slim-Csrf#58]
I'm looking to replace the native `$_SESSION` superglobal in my app with [Laravel sessions](https://github.com/illuminate/session).  Laravel's sessions seem to build, in turn, on [Symfony sessions](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Session/Session.php), which implement `IteratorAggregate` and `Countable`.  However, they notably do *not* implement `ArrayAccess`, which appears to be required for Slim-Csrf:

```
    /**
     * CSRF storage
     *
     * Should be either an array or an object. If an object is used, then it must
     * implement ArrayAccess and should implement Countable and Iterator (or
     * IteratorAggregate) if storage limit enforcement is required.
     *
     * @var array|ArrayAccess
     */
    protected $storage;
```

How difficult would it be to relax this requirement?  Would an adapter be needed to fetch and store data from the Laravel/Symfony sessions?

**Comment by geggleto** [comment]
It would more or less require a gutting of the middleware ... Interesting choice using Laravel, I would recommend the Zend session packages personally.

You can always Wrap the Laravel Session Object, and implement Array Access...

**Comment by alexweissman** [comment]
I ended up wrapping the native `$_SESSION` superglobal in my [own session package](https://github.com/userfrosting/session/), which implements `ArrayAccess`.  So, hopefully this will work nicely with Slim-Csrf.
