### ISSUE TITLE
add redirect to setFailureCallable

### ISSUE THREAD

**Issue by X-Tender** [slimphp/Slim-Csrf#64]
I've added the `setFailureCollabel` to my code but I ran into a small problem.
That's my code:
```
$guard->setFailureCallable(function ($request, $response, $next) use ($c) {
    $response = $response->withRedirect( $c->get('router')->pathFor('index'));
    return $next($request, $response);
});
```
So when the CSRF failed I would like to redirect the User to the index route.
The problem is that slim itself still continue to run my code so the authentification process which i have in my login POST route code gets called and the user gets logged in.

So my question is, is there a way to tell slim in the `setFailureCallable` that he have to please quit everything and just to the redirect richt now?

The workaround would be here to use the example with `withAttribute` but then I had to add a IF block in every POST route code to check if it is false and then don't execute the POST code.

**Comment by X-Tender** [comment]
Oh man, I think I solved it (why did that always happen after creating an issue)

```
$next($request, $response);
$response = $response->withRedirect( $c->get('router')->pathFor('index'));
return $response;
```

That's all.. seems to work.

**Comment by akrabat** [comment]
That looks right to me. No need to call next in this case, so you can return the response.
