### ISSUE TITLE
How to instantiate with $persistentTokenMode = true

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim-Csrf#69]
In order to use persistent tokens, you advise to "set the sixth parameter of the constructor to true." Considering future updates, is there a more flexible way to e.g. instantiate with true other than hard-coding the value in the constructor itself? I tried it the following way, and verified that $persistentTokenMode was indeed true. However, the names and keys were then empty in the route view:

    $app->add($container->get('csrf'));
    $container->csrf->setPersistentTokenMode(true);

Hard-coding $persistentTokenMode = true also results in empty values. (I'm using Twig)

**Comment by matthiashagemann** [comment]
Upon further testing, $this->storage is simply empty if $persistentTokenMode = true

**Comment by alexweissman** [comment]
Hey, I implemented this feature!

Considering that PHP doesn't support named parameters, at this point it might be more useful if the ctor simply accepted an `options` array with key-value pairs for the parameters.

@akrabat what do you think about this?  Obviously it would be BC, but it could be implemented in the next major release.

@matthiashagemann as for your issue with Twig, are you using the [sample extension](https://github.com/slimphp/Slim-Csrf#accessing-the-token-pair-in-templates-twig-etc)?

**Comment by matthiashagemann** [comment]
Thanks @alexweissman! It worked nicely with the sample. Should have rtfm.

**Comment by dvikan** [comment]
Turning on persistentmode with the setter causes empty attributes on the request
$name = $request->getAttribute($nameKey); // empty

**Comment by ivandokov** [comment]
@dvikan my PR here https://github.com/slimphp/Slim-Csrf/pull/67 is fixing this issue. @akrabat should take a look at it.

**Comment by andreasschroth** [comment]
First of all... Thanks for the good work! :)

We are running into this problem as well and as we work with a SPA and AJAX requests, regenerating a token after every failed form submission is not the preferred way by us.

Please merge the PR.

**Comment by JuniorOcheiRuiz** [comment]
This is working good:

```
$container['csrf'] = function ($c) {
    $csrf = new \Slim\Csrf\Guard;
    $csrf->setPersistentTokenMode(true);
    return $csrf;
};
```
