### ISSUE TITLE
Managing CSRF with cookies disabled

### ISSUE THREAD

**Issue by tomntech** [slimphp/Slim-Csrf#71]
The middleware makes use of PHP Sessions, which in turn requires cookies to be enabled on the web application. Some users set their browser to disable all cookies and as such the middleware will return a 400 error. Is there a way we can either a) re-route if cookies are not enabled or b) make use of an alternative store other than PHP Sessions?

**Comment by odan** [comment]
It would be possible by defining a [custom PHP session handler](http://php.net/manual/en/class.sessionhandler.php) before the Slim CSRF middleware is getting invoked. 

```php
$handler = new MyCustomSessionHandler();
session_set_save_handler($handler, true);
```
