### ISSUE TITLE
Session generate on each reload and did not clear the old session.

### ISSUE THREAD

**Issue by ve3** [slimphp/Slim-Csrf#73]
I use this manual code

```php
session_start();

$slimGuard = new \Slim\Csrf\Guard;
$slimGuard->validateStorage();

// Generate new tokens
$csrfNameKey = $slimGuard->getTokenNameKey();
$csrfValueKey = $slimGuard->getTokenValueKey();
$keyPair = $slimGuard->generateToken();

// and put those name, value, keypair into input hidden.
```

and then write out the sessions.

```php
echo '<pre>'.print_r($_SESSION, true).'</pre>'."\n";
```

Every time I reload the page, it generate new token session and did not clear the old one.
12 times of page load means 12 sessions and more...

I think this make a lot of junk token that is never use. How to clear the old session before generate the new one? Or is this a bug?

**Comment by n4mlih** [comment]
refering to this [#69](https://github.com/slimphp/Slim-Csrf/issues/69), try using `presistentTokenMode` or `unset($_SESSION["csrf"]);`
