### ISSUE TITLE
Access CSRF from inside notFoundHandler?

### ISSUE THREAD

**Issue by edwardteach42** [slimphp/Slim-Csrf#74]
Is there any way to get the CSRF twig extension into the notFoundHandler? It works great on all pages except the handlers.

**Comment by geggleto** [comment]
Well you would need to create a new NotFoundHandler that uses Twig.
It's simple-ish enough to do.
Extend current Not Found Handler, add new constructor parameter.
Replace NotFoundHanlder in the slim container.
