### ISSUE TITLE
Cannot unset string offsets

### ISSUE THREAD

**Issue by CorvinSteindl** [slimphp/Slim-Csrf#75]
I integrated Slim-Csrf like in the description and it works fine with php´s own webserver but if i try to work on a apache server the following appear on a post request:

![slim_csrf_error](https://user-images.githubusercontent.com/13137313/28221283-0021dca6-68c3-11e7-81b3-3508bf219d66.png)

Any Ideas?

**Comment by geggleto** [comment]
Looks like something in your session configuration is wrong.
