### ISSUE TITLE
Cannot get request's nameKey and valueKey when 'setPersistentTokenMode' is set to true

### ISSUE THREAD

**Issue by CWaYNe** [slimphp/Slim-Csrf#76]
After setting `PersistentTokenMode` to true, `$request->getAttribute($nameKey)` and `$request->getAttribute($valueKey)` will be null. 

However, using `getTokenName` and `getTokenValue` is working properly. I am aware that  PR #67  should be fixing this issue, but it is still not working properly. Any suggestions? Thanks!

```
    // CSRF token name and value
    $nameKey = $this->csrf->getTokenNameKey();
    $valueKey = $this->csrf->getTokenValueKey();
    $name = $this->csrf->getTokenName();
    $value = $this->csrf->getTokenValue();

    // NOT WORKING WHEN Token is persistent
    // $name = $request->getAttribute($nameKey);
    // $value = $request->getAttribute($valueKey);
```

**Comment by ivandokov** [comment]
The PR #67 is still not merged. Waiting for @akrabat to merge/comment it.

**Comment by CWaYNe** [comment]
Ok! Thanks!
