### ISSUE TITLE
New token on each page load

### ISSUE THREAD

**Issue by Grafikart** [slimphp/Slim-Csrf#78]
This is more a question than an issue but it can lead to a PR.

## The problem

This middleware generates a new token for each request and use the request attribute to pass this token along. Some pages doesn't have forms (a csrf token is not needed) but this middleware will query the session and generate a token anyway.
Another issue happens if we have 2 forms on the same page that can be submitted using ajax (with persistent set to false). It's more an edge but it can happen.

## Proposed solution

I think a better solution would be to "store" a new token when we generate a new one. This way the session won't be modified when token aren't necessary. Moreover we won't have to pass the request to the token generator making dependency injection (I'm not a huge fan of using request within my container).

```php
// The middleware will be the same
$app->add(Guard::class)
// but the generator will be different
$container->get(Guard::class)->getTokenValueKey() // string
$container->get(Guard::class)->generateToken() // string
// maybe offer an helper
$container->get(Guard::class)->input()
```

I think it could be a better solution but this change will break the backward compatibility. So there is 2 solutions :

- Create a new Guard (RequestIndependentGuard) 
- Create a new library (if you don't think this should be included for slim)

Thanks

**Comment by geggleto** [comment]
The solution to your problem, is to not attach the middleware to the routes that do not need CSRF.

In slim you can be very specific about that.

```php

//routes that do not need

//routes that do need.
$app->group('', function () {
   $this->get('/myform', MyFormAction::class);
})->add(Guard::class);

```

**Comment by Grafikart** [comment]
@geggleto that was my first lead, but the form is displayed only if the user is logged in. Like I said this is a suggestion that would change the behaviour of this middleware, this is why I asked If it is worth implementing here before publishing yet another csrf middleware.  
Another solution, like you stated would be to use route grouping, or include slim middleware within my domain specific middleware. Feel free to close this issue if you think this should be in the domain logic instead of here.

**Comment by geggleto** [comment]
Your proposed change would be considered a backwards compatibility break ;) I think storing these tokens is not such a good idea. Applying the middleware only where you need it is the proper solution.
CSRF is most definitely should not be applied globally; perhaps we should update the example :)

**Comment by Grafikart** [comment]
The problem is specific to my use case and it's not worth changing how thing works for one case (I created a custom middlewarea for my use case).

**Comment by akrabat** [comment]
You could also use the mode where it generates one token per session.

**Comment by Grafikart** [comment]
@akrabat Persistent mode will try to generate (and retrieve) a token for every page, forcing me to start the session (even if the page doesn't contain a form). I closed this issue since it appeared to be an edge case.
