### ISSUE TITLE
Problem with cross-domain ajax

### ISSUE THREAD

**Issue by rusbitdev** [slimphp/Slim-Csrf#79]
Hi people. I'm using Slim for REST API and Vue2  + Webpack for frontend. 

I want to make POST request, data is sending good, but slim said: 'Failed check csrf', i made route to return csrf_name and csrf_token, for example: 

get CsrfToken.php
```
<?php
/**
 * @var $csrf \Slim\Csrf\Guard
 */
$csrf = $this->container->get('csrf');

print json_encode($csrf->generateToken());
?>
```

and my ajax is:
```
<script>
    fetch('/', {
        method: 'post',
        credentials: 'include',
        headers: {
            'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8'
        },
        body: 'csrf_name=csrfName&csrf_value=csrfValue'
    })
        .then(function (response) {
            return response.text();
        })
        .then(function (response) {
            console.log(response);
        })
</script>
```

Tell me pls, what i am doing wrong?and how do I make a POST request?

**Comment by dev-yann** [comment]
I have the same problem ! it is resolve for you ?

**Comment by Auramel** [comment]
It's not good, but try to use setPersistentTokenMode(true)
