### ISSUE TITLE
API csrf

### ISSUE THREAD

**Issue by Shelko** [slimphp/Slim-Csrf#83]
Hi, i'm using Slim Framework as my first framework and i saw videos about how works it. It's simple and great but i have hm... doubts...

I'm doing a web service with Csrf and works well but i have problems cause i'm trying to **sign up** or **sign in** with a **smartphone**. Well... I did **ajax** the problem is the **CSRF** i'm trying to **disable** for **some** kind of **routes** without success.

I'm trying to find an example for **dummies** ^^'.

I tried to delete the "add(container->csrf)" from kernel to add it to every route but it doesn't work.

Thanks for your time!

**Comment by akrabat** [comment]
If you're using ajax, try setting the token persistence setting: https://github.com/slimphp/Slim-Csrf#token-persistence

**Comment by Shelko** [comment]
So i have to send to the client the **token** into the **header** and then when i **submit** the **form** send those **tokens**? I have to say that i forgot comment that the **API** is for an **Android App** done with **Cordova**.
