### ISSUE TITLE
Session Expires Quickly

### ISSUE THREAD

**Issue by rafecolton** [slimphp/Slim-Csrf#99]
Hello,

I am using the Gaurd with the following arguments:

```php
new \Slim\Csrf\Guard('csrf', $_, function(Request $request, Response $response, $next) {
  return $response
    ->withStatus(400)
    ->withHeader('Content-type', 'text/plain')
    ->write('Security check failed. Please refresh the page.');
}, 200, 16, true));
```

I have users reporting that when they leave the page sit 30–60 minutes, the CSRF check fails on the next API request. I have been able to reproduce this on Mobile Safari on iOS. As far as I know, nothing is killing the session, as the user is still logged in. Any idea why this would be happening? I don't see anything in the code about how long to keep the tokens, so I would expect them to last as long as the session.

**Comment by C0kkie** [comment]
Any news on that? I have sometimes the same problem

**Comment by C0kkie** [comment]
Nobody? :O

**Comment by l0gicgate** [comment]
I’m not familiar with this lib. @akrabat @geggleto?

**Comment by akrabat** [comment]
I have no clue why that would happen as the code doesn't do anything clever. I think that the session is being expired either by PHP or by the[ Linux distro's cleanup code](https://serverfault.com/questions/511609/why-does-debian-clean-php-sessions-with-a-cron-job-instead-of-using-phps-built).

**Comment by C0kkie** [comment]
The thing is, the session is still present as in the first post written @akrabat

**Comment by akrabat** [comment]
@C0kkie I don't know how to help. I can't see anything in the [source](https://github.com/slimphp/Slim-Csrf/blob/master/src/Guard.php) related to timing out as it just uses `$_SESSION`. 

Logically `$_SESSION` must no longer have the info in it. The obvious ways that this could happen is if PHP gc'd the session or the storage limit was reached. The storage limit is 200, so maybe raise it to 1000 and see if that solves it? If it does, you should work out what is causing your user to make 199 requests to the site before submitting the form they are supposed to be filling out.

**Comment by C0kkie** [comment]
What variables is the limit in the php ini?

**Comment by akrabat** [comment]
> What variables is the limit in the php ini?

If you mean storage limit, it's a [constructor parameter](https://github.com/slimphp/Slim-Csrf/blob/master/src/Guard.php#L93) to `Guard`.

**Comment by C0kkie** [comment]
I will set it 1000 and will see if that solves it,

**Comment by C0kkie** [comment]
Looks like it didnt helped to set it to 1000, users still complaining about it

**Comment by akrabat** [comment]
Not that then. You'll have to debug it. Can you reproduce on your staging environment?

**Comment by C0kkie** [comment]
Mostly yes, if i wait a hour or something like that

**Comment by C0kkie** [comment]
But not really a idea how to debug that shit :D

**Comment by C0kkie** [comment]
a higher session.gc_maxlifetime solved my problem, it was because the session got deleted while someone filled a form

**Comment by l0gicgate** [comment]
Thanks for the update @C0kkie. Closing this as resolved
